### ISSUE TITLE
Change everything to androidx.* package structure

### ISSUE THREAD

**Issue by weverb2** [atomicrobot/android-starter-project#65]
Once things come out of alpha.

Reference:
https://developer.android.com/topic/libraries/support-library/refactor

**Comment by stuartsoft** [comment]
~Once things come out of alpha.~
NO! DO IT NOW!
<img src="https://memegenerator.net/img/instances/16838118.jpg" width="200px"/>

**Comment by patrickhammond** [comment]
It's been done.
https://github.com/atomicrobot/android-starter-project/pull/79
